name: "Setup dependencies"
description: "Prepare repository and all dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v2
      with:
          version: 8

    - name: Setup Node.js 20.x
      uses: actions/setup-node@v3
      with:
          node-version: 20.x
          cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install
