name: Verify
on: push

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              uses: ./.github/actions/setup

            - name: Lint code
              run: pnpm lint

    build:
        name: Build
        needs: lint
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              uses: ./.github/actions/setup

            - name: Build
              run: pnpm build

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install dependencies
              uses: ./.github/actions/setup

            - name: Run tests
              uses: nick-fields/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 3
                  command: pnpm test
